package testchipip.cosim

import chisel3._
import chisel3.experimental.{IntParam, StringParam}
import chisel3.util._

import freechips.rocketchip.subsystem._
import freechips.rocketchip.diplomacy._
import freechips.rocketchip.devices.tilelink._
import freechips.rocketchip.util._



class GeneralSpikeCosim(cfg: SpikeCosimConfig,width:Int) extends BlackBox(Map(
  "ISA" -> StringParam(cfg.isa),
  "PRIV" -> StringParam(cfg.priv),
  "PMPREGIONS" -> IntParam(cfg.pmpregions),
  "MAXPGLEVELS" -> IntParam(cfg.maxpglevels),
  "MEM0_BASE" -> IntParam(cfg.mem0_base),
  "MEM0_SIZE" -> IntParam(cfg.mem0_size),
  "MEM1_BASE" -> IntParam(cfg.mem1_base),
  "MEM1_SIZE" -> IntParam(cfg.mem1_size),
  "MEM2_BASE" -> IntParam(cfg.mem2_base),
  "MEM2_SIZE" -> IntParam(cfg.mem2_size),
  "NHARTS" -> IntParam(cfg.nharts),
  "BOOTROM" -> StringParam(cfg.bootrom)
)) with HasBlackBoxResource with HasBlackBoxInline
{
  addResource("/testchipip/csrc/cospike.cc")
  addResource("/testchipip/csrc/cospike_impl.cc")
  addResource("/testchipip/csrc/cospike_impl.h")
  // addResource("/rocket-chip/src/main/resources/csrc/verilator.h")
  // addResource("/testchipip/vsrc/cospike.v")
  if (cfg.has_dtm) addResource("/testchipip/csrc/cospike_dtm.h")
  println("Enable Spike Co-simulation with " + width + " trace channels.")
  val io = IO(new Bundle {
    val clock = Input(Clock())
    val reset = Input(Bool())
    val cycle = Input(UInt(64.W))
    val hartid = Input(UInt(64.W))
    val trace = Input(Vec(width, new Bundle {
      val valid = Bool()
      val iaddr = UInt(64.W)
      val insn = UInt(32.W)
      val exception = Bool()
      val interrupt = Bool()
      val cause = UInt(64.W)
      val has_wdata = Bool()
      val wdata = UInt(64.W)
      val priv = UInt(3.W)
    }))
  })
  // Helper function to generate the port list string
  def genPorts(n: Int): String = {
    // Iterate from 0 to n-1 to create port declarations for each trace channel
    (0 until n).map { i =>
      s"""|    input trace_${i}_valid,
          |    input [63:0] trace_${i}_iaddr,
          |    input [31:0] trace_${i}_insn,
          |    input trace_${i}_exception,
          |    input trace_${i}_interrupt,
          |    input [63:0] trace_${i}_cause,
          |    input trace_${i}_has_wdata,
          |    input [63:0] trace_${i}_wdata,
          |    input [2:0] trace_${i}_priv""".stripMargin
    }.mkString(",\n") // Join each port group with a comma and a newline
  }

 def genLogic(n: Int): String = {
    // Iterate from 0 to n-1 to create an 'if' block for each trace channel
    (0 until n).map { i =>
      s"""
         |        if (trace_${i}_valid || trace_${i}_exception || (trace_${i}_cause != 0)) begin
         |            if (cospike_cosim_wrapper(cycle, hartid, trace_${i}_has_wdata, trace_${i}_valid, trace_${i}_iaddr,
         |                          trace_${i}_insn, trace_${i}_exception, trace_${i}_interrupt, trace_${i}_cause,
         |                          trace_${i}_wdata, trace_${i}_priv) != 0) begin
         |                $$fatal("Spike cosimulation failed!");
         |            end
         |        end""".stripMargin
    }.mkString("\n") // Join each 'if' block with a newline
  }

  setInline("cospike.v",
    s"""
// This file is generated by Chisel
import "DPI-C" function void cospike_set_sysinfo_wrapper(
                                                 input string  isa,
                                                 input string  priv,
                                                 input int     pmpregions,
                                                 input int     maxpglevels,
                                                 input longint mem0_base,
                                                 input longint mem0_size,
                                                 input longint mem1_base,
                                                 input longint mem1_size,
                                                 input longint mem2_base,
                                                 input longint mem2_size,
                                                 input int     nharts,
                                                 input string  bootrom
                                                 );

// 修改返回值类型为 int
import "DPI-C" function int cospike_cosim_wrapper(input longint cycle,
                                           input longint hartid,
                                           input bit     has_wdata,
                                           input bit     valid,
                                           input longint iaddr,
                                           input int     insn,
                                           input bit     raise_exception,
                                           input bit     raise_interrupt,
                                           input longint cause,
                                           input longint wdata,
                                           input int     priv
                                           );

module GeneralSpikeCosim #(
    parameter ISA,
    parameter PRIV,
    parameter PMPREGIONS,
    parameter MAXPGLEVELS,
    parameter MEM0_BASE,
    parameter MEM0_SIZE,
    parameter MEM1_BASE,
    parameter MEM1_SIZE,
    parameter MEM2_BASE,
    parameter MEM2_SIZE,
    parameter NHARTS,
    parameter BOOTROM
) (
    input clock,
    input reset,
    input [63:0] cycle,
    input [63:0] hartid
    ${if (width > 0) "," else ""} ${genPorts(width)}
);

  initial begin
    cospike_set_sysinfo_wrapper(ISA, PRIV, PMPREGIONS, MAXPGLEVELS,
                                MEM0_BASE, MEM0_SIZE,
                                MEM1_BASE, MEM1_SIZE,
                                MEM2_BASE, MEM2_SIZE,
                                NHARTS, BOOTROM);
  end;

  always @(posedge clock) begin
    if (!reset) begin
${genLogic(width)}
    end
  end

endmodule
""")
}

object GeneralSpikeCosim
{
  def apply(trace: TileTraceIO, hartid: Int, cfg: SpikeCosimConfig) = {
    val cosim = Module(new GeneralSpikeCosim(cfg,trace.numInsns))
    val cycle = withClockAndReset(trace.clock, trace.reset) {
      val r = RegInit(0.U(64.W))
      r := r + 1.U
      r
    }
    cosim.io.clock := trace.clock
    cosim.io.reset := trace.reset
    // require(trace.numInsns <= 2)
    cosim.io.cycle := cycle
    cosim.io.trace.map(t => {
      t := DontCare
      t.valid := false.B
    })
    cosim.io.hartid := hartid.U
    for (i <- 0 until trace.numInsns) {
      val insn = trace.trace.insns(i)
      cosim.io.trace(i).valid := insn.valid
      val signed = Wire(SInt(64.W))
      signed := insn.iaddr.asSInt
      cosim.io.trace(i).iaddr := signed.asUInt
      cosim.io.trace(i).insn := insn.insn
      cosim.io.trace(i).exception := insn.exception
      cosim.io.trace(i).interrupt := insn.interrupt
      cosim.io.trace(i).cause := insn.cause
      cosim.io.trace(i).has_wdata := insn.wdata.isDefined.B
      cosim.io.trace(i).wdata := insn.wdata.getOrElse(0.U)
      cosim.io.trace(i).priv := insn.priv
    }
  }
}

