package voyager_tapeout.custom.iobinders

import chisel3._
import chisel3.experimental.{Analog}
import org.chipsalliance.cde.config.{Parameters}
import voyager_tapeout.custom.device.peripheral_npu.{PeripheralNPUPunchthroughIO}

trait Port[T <: Data] {
  val getIO: () => T
  // port.io should only be called in the TestHarness context
  lazy val io = getIO()
}

trait HasChipyardPorts {
  def ports: Seq[Port[_]]
}

// These case classes are generated by IOBinders, and interpreted by HarnessBinders
case class PeripheralNPUPort (val getIO: () => PeripheralNPUPunchthroughIO)
    extends Port[PeripheralNPUPunchthroughIO]
