// Generated by CIRCT firtool-1.75.0
module ClockMutexMux(	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:86:7]
  input  io_clocksIn_0,	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:88:16]
  input  io_clocksIn_1,	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:88:16]
  output io_clockOut,	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:88:16]
  input  io_resetAsync,	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:88:16]
  input  io_sel	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:88:16]
);

  wire _gaters_1_out;	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:99:23]
  wire _gaters_0_out;	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:99:23]
  wire _syncs_1_io_q;	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83]
  wire _syncs_0_io_q;	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83]
  wire _andClocks_x_3_clockOut;	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
  wire _andClocks_x_2_clockOut;	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:45:23]
  wire _andClocks_x_1_clockOut;	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
  wire _andClocks_x_clockOut;	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:45:23]
  ClockInverter andClocks_x (	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:45:23]
    .clockIn  (io_clocksIn_0),
    .clockOut (_andClocks_x_clockOut)
  );	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:45:23]
  ClockSignalNor2 andClocks_x_1 (	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
    .clockIn  (_andClocks_x_clockOut),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:45:23]
    .signalIn (io_resetAsync),
    .clockOut (_andClocks_x_1_clockOut)
  );	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
  ClockInverter andClocks_x_2 (	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:45:23]
    .clockIn  (io_clocksIn_1),
    .clockOut (_andClocks_x_2_clockOut)
  );	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:45:23]
  ClockSignalNor2 andClocks_x_3 (	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
    .clockIn  (_andClocks_x_2_clockOut),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:45:23]
    .signalIn (io_resetAsync),
    .clockOut (_andClocks_x_3_clockOut)
  );	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
  AsyncResetSynchronizerShiftReg_w1_d3_i0_3 syncs_0 (	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83]
    .clock (_andClocks_x_1_clockOut),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
    .reset (io_resetAsync),
    .io_d  (~io_sel & ~_syncs_1_io_q),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83, :107:{67,76,79}]
    .io_q  (_syncs_0_io_q)
  );	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83]
  AsyncResetSynchronizerShiftReg_w1_d3_i0_3 syncs_1 (	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83]
    .clock (_andClocks_x_3_clockOut),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
    .reset (io_resetAsync),
    .io_d  (io_sel & ~_syncs_0_io_q),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83, :107:{76,79}]
    .io_q  (_syncs_1_io_q)
  );	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83]
  EICG_wrapper gaters_0 (	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:99:23]
    .in      (_andClocks_x_1_clockOut),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
    .test_en (1'h0),
    .en      (_syncs_0_io_q),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83]
    .out     (_gaters_0_out)
  );	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:99:23]
  EICG_wrapper gaters_1 (	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:99:23]
    .in      (_andClocks_x_3_clockOut),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:63:23]
    .test_en (1'h0),
    .en      (_syncs_1_io_q),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:97:83]
    .out     (_gaters_1_out)
  );	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:99:23]
  ClockOr2 ClockOr2 (	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:115:62]
    .clocksIn_0 (_gaters_0_out),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:99:23]
    .clocksIn_1 (_gaters_1_out),	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:99:23]
    .clockOut   (io_clockOut)
  );	// @[generators/testchipip/src/main/scala/clocking/ClockUtil.scala:115:62]
endmodule

