name: Voyager CI
run-name: ${{ github.actor }} is running CI Test 🚀
on:
  push:
    branches:
      - dev

jobs:
  Code-Pull:
    name: Code Pull
    runs-on: fpga
    steps:
      - name: Print information
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Pull from the repository
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard origin/${{ github.ref }}
          git pull origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "🍏 pull from repository ${{ job.status }}."

  Pre-commit-check:
    name: Pre-commit Check
    runs-on: fpga
    needs: Code-Pull
    steps:
      - name: Verify pre-commit proof
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          ./.github/scripts/ci-pre-commit-check.sh
      - run: echo "🍏 pre-commit proof verification is ${{ job.status }}."
      # 如果检查失败，强制回退分支
      - name: Revert Bad Commit
        if: failure()
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard HEAD~1
          git push --force origin ${{ github.ref }}
          echo "🍏 Please Do Pre-commit Before Commit!!!" 

  Build-Workloads:
    name: Build Workloads
    runs-on: fpga
    needs: Pre-commit-check
    steps:
      - name: Build Workloads
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          cd voyager-test
          rm -rf build 
          mkdir -p build && cd build
          cmake ..
          make build-all
      - run: echo "🍏 Workloads build is ${{ job.status }}."
      - name: Revert Bad Commit
        if: failure()
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard HEAD~1
          git push --force origin ${{ github.ref }}
  
  Build-Verilator:
    name: Build Verilator
    runs-on: fpga
    needs: Build-Workloads
    steps:
      - name: Build Verilator
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          ./voyager-test/scripts/build-verilator.sh --config VoyagerVerilatorConfig --project voyager_tapeout --sub-project voyager_tapeout --debug
        # 如果检查失败，强制回退分支
      - name: Revert Bad Commit
        if: failure()
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard HEAD~1
          git push --force origin ${{ github.ref }}
  
  Smoke-Test:
    name: Smoke Test
    runs-on: fpga
    needs: Build-Verilator
    steps:
      - name: Smoke Test
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          cd voyager-test/scripts/sardine
          python run_tests.py --allure -m smoke
      - run: echo "🍏 Smoke Test is ${{ job.status }}."
        # 如果检查失败，强制回退分支
      - name: Revert Bad Commit
        if: failure()
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard HEAD~1
          git push --force origin ${{ github.ref }}

  # ============== 专用测试 ==================
  # NPU测试: 匹配到[npu-test]才会执行
  # NPU-Specific-Test:
  #   name: NPU Specific Test
  #   runs-on: fpga
  #   needs: Lint-and-Test
  #   if: contains(github.event.head_commit.message, '[npu-test]') 
  #   steps:
  #     - name: Run NPU Specific Test
  #       shell: zsh {0}
  #       run: |
  #         source ~/.zshrc
  #         chipyard_exec
  #         echo "🚀 Running NPU Specific Test..."
  #         echo "Triggered by commit: ${{ github.event.head_commit.message }}"
  #         ./voyager-test/scripts/batch-test.sh --npu-test
  #     - run: echo "🍏 NPU Specific Test is ${{ job.status }}."
  #     # 如果检查失败，强制回退分支
  #     - name: Revert Bad Commit
  #       if: failure()
  #       shell: zsh {0}
  #       run: |
  #         source ~/.zshrc
  #         chipyard_exec
  #         setproxy
  #         git reset --hard HEAD~1
  #         git push --force origin ${{ github.ref }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # # Meek测试: 匹配到[meek-test]才会执行
  # Meek-Specific-Test:
  #   name: Meek Specific Test
  #   runs-on: fpga
  #   needs: Lint-and-Test
  #   if: contains(github.event.head_commit.message, '[meek-test]') 
  #   steps:
  #     - name: Run Meek Specific Test
  #       shell: zsh {0}
  #       run: |
  #         source ~/.zshrc
  #         chipyard_exec
  #         echo "🚀 Running Meek Specific Test..."
  #         echo "Triggered by commit: ${{ github.event.head_commit.message }}"
  #         ./voyager-test/scripts/batch-test.sh --meek-test
  #     - run: echo "🍏 Meek Specific Test is ${{ job.status }}."
  #     # 如果检查失败，强制回退分支
  #     - name: Revert Bad Commit
  #       if: failure()
  #       shell: zsh {0}
  #       run: |
  #         source ~/.zshrc
  #         chipyard_exec
  #         setproxy
  #         git reset --hard HEAD~1
  #         git push --force origin ${{ github.ref }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # # DC 测试: 匹配到[dc-eval]才会执行，失败不会退回
  # DC-Evaluation:
  #   name: DC Area Evaluation
  #   runs-on: fpga
  #   needs: Lint-and-Test
  #   if: contains(github.event.head_commit.message, '[dc-eval]')
  #   steps:
  #     - name: Run DC Evaluation
  #       shell: zsh {0}
  #       run: |
  #         source ~/.zshrc
  #         chipyard_exec
  #         echo "🚀 Running DC Evaluation..."
  #         echo "Triggered by commit: ${{ github.event.head_commit.message }}"
  #         ./voyager-test/scripts/run-dc.sh --config VoyagerChipConfig 


# ============== 测试结束 ==================

  Update-Repository:
    name: Update Repository
    runs-on: fpga
    needs: Smoke-Test
    steps:
      - run: echo "🎉 Good Job! This ${{ github.event_name }} will be updated to ${{ github.ref }}."