name: Voyager CI
run-name: ${{ github.actor }} is running CI Test 🚀
on:
  push:
    branches:
      - dev

jobs:
  Code-Pull:
    name: Code Pull
    runs-on: fpga
    steps:
      - name: Print information
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Pull from the repository (with update)
        shell: zsh {0}
        if: contains(github.event.head_commit.message, '<need pull-with-update>')
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard origin/${{ github.ref }}
          git pull-with-update origin ${{ github.ref }}
      - name: Pull from the repository (normal)
        shell: zsh {0}
        if: "!contains(github.event.head_commit.message, '<need pull-with-update>')"
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard origin/${{ github.ref }}
          git pull origin ${{ github.ref }}
      - run: echo "🍏 pull from repository ${{ job.status }}."

  Pre-commit-check:
    name: Pre-commit Check
    runs-on: fpga
    needs: Code-Pull
    steps:
      - name: Verify pre-commit proof
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          ./.github/scripts/ci-pre-commit-check.sh
      - run: echo "🍏 pre-commit proof verification is ${{ job.status }}."
      # 如果检查失败，强制回退分支
      - name: Revert Bad Commit
        if: failure()
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard HEAD~1
          git push --force origin ${{ github.ref }}
          echo "🍏 Please Do Pre-commit Before Commit!!!" 

  Build-Workloads:
    name: Build Workloads
    runs-on: fpga
    needs: Pre-commit-check
    steps:
      - name: Build Workloads
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          cd voyager-test
          rm -rf build 
          mkdir -p build && cd build
          cmake ..
          make build-all
      - run: echo "🍏 Workloads build is ${{ job.status }}."
      - name: Revert Bad Commit
        if: failure()
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard HEAD~1
          git push --force origin ${{ github.ref }}
  
  Build-Verilator:
    name: Build Verilator
    runs-on: fpga
    needs: Build-Workloads
    steps:
      - name: Build Verilator
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          ./tapeout/scripts/voyager-code-gen.sh --tool verilator --config VoyagerVerilatorConfig
        # 如果检查失败，强制回退分支
      - name: Revert Bad Commit
        if: failure()
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard HEAD~1
          git push --force origin ${{ github.ref }}
  
  Build-VCS:
    name: Build VCS
    runs-on: fpga
    needs: Build-Workloads
    steps:
      - name: Build VCS
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          ./tapeout/scripts/voyager-code-gen.sh --tool vcs --config VoyagerVcsConfig 
        # 如果检查失败，强制回退分支
      - name: Revert Bad Commit
        if: failure()
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard HEAD~1
          git push --force origin ${{ github.ref }}
  
  Smoke-Test:
    name: Smoke Test
    runs-on: fpga
    needs: Build-Verilator
    steps:
      - name: Smoke Test
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          cd voyager-test/scripts/sardine
          python run_tests.py --allure -m "(smoke or embench or buckyball) and not debug"
      - run: echo "🍏 Smoke Test is ${{ job.status }}."
        # 如果检查失败，强制回退分支
      - name: Revert Bad Commit
        if: failure()
        shell: zsh {0}
        run: |
          source ~/.zshrc
          chipyard_exec
          setproxy
          git reset --hard HEAD~1
          git push --force origin ${{ github.ref }}

  # VCS-Test:
  #   name: VCS Test
  #   runs-on: fpga
  #   needs: Build-VCS
  #   steps:
  #     - name: VCS Test
  #       shell: zsh {0}
  #       run: |
  #         source ~/.zshrc
  #         chipyard_exec
  #         cd voyager-test/scripts/sardine
  #         python run_tests.py -m "vcs and (embench or buckyball) and debug" 
  #     - run: echo "🍏 VCS Test is ${{ job.status }}."
  #       # 如果检查失败，强制回退分支
  #     - name: Revert Bad Commit
  #       if: failure()
  #       shell: zsh {0}
  #       run: |
  #         source ~/.zshrc
  #         chipyard_exec
  #         setproxy
  #         git reset --hard HEAD~1
  #         git push --force origin ${{ github.ref }}
  
# ============== 测试结束 ==================

  Update-Repository:
    name: Update Repository
    runs-on: fpga
    needs: Smoke-Test
    steps:
      - run: echo "🎉 Good Job! This ${{ github.event_name }} will be updated to ${{ github.ref }}."